# k8s/deployment-demo-secret-env-var.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
        labels:
          app: nginx
    spec:
      containers:
      - name: server
        image: nginx:1.26.0
        env:
          - name: NGINX_WORKER_PROCESSES
            value: "2"
          - name: NG_USERNAME
            valueFrom:
              secretKeyRef:
                name: nginx-creds
                key: username
          - name: NG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nginx-creds
                key: password