# k8s/hpa-autoscaler-demo.yaml

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: netflix-frontend-hpa-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: netflix-frontend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50